parameters:
    database_driver:   pdo_sqlite
    database_host:     localhost
    database_port:     ~
    database_name:     sqlite.db
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            ja
    secret:            ThisTokenIsNotSoSecretChangeIt
